/**
 * dsh-token-usage — Client(web) 构建脚本
 *
 * 产物契约 (DSH client-modules):
 *   window.__ModuleLoader__.load({
 *     id: "<包名>",
 *     factory: (require) => { ... return module.exports }
 *   })
 * - classic <script> 加载, factory 是 CJS 闭包, 接收运行时 require
 * - react / react/jsx-runtime / styles / host 由运行时 seed, 外部化
 *
 * 构建: node client/build.mjs   (内部调用 npx esbuild 转译 JSX + import)
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "client", "index.js");
const outDir = join(root, "client", "dist");
const outFile = join(outDir, "index.js");
const tmpFile = join(outDir, "_inner.cjs");
const PACKAGE_ID = "@wycto/dsh-token-usage";

function runEsbuild(args) {
  // npx 自动解析 esbuild (含 npx 缓存); Windows 下经 shell 调用
  // stdio: inherit — esbuild 输出直通终端, 不捕获管道(沙箱/CI 下避免管道 EPERM)
  try {
    execSync(`npx --yes esbuild ${args.map((a) => JSON.stringify(a)).join(" ")}`, {
      stdio: "inherit",
      shell: process.platform === "win32",
    });
  } catch (e) {
    throw new Error(`esbuild failed: ${e.message || e}`);
  }
}

mkdirSync(outDir, { recursive: true });

// 1. 转译源码 → CJS (不 bundle, JSX→automatic runtime, import→require)
runEsbuild([
  src,
  "--format=cjs",
  "--platform=browser",
  "--jsx=automatic",
  "--loader:.js=jsx",
  "--outfile=" + tmpFile,
  "--log-level=warning",
]);

// 2. 包闭包壳
const banner = `/* dsh-token-usage client bundle — generated by client/build.mjs */
window.__ModuleLoader__.load({
	id: ${JSON.stringify(PACKAGE_ID)},
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
`;
const footer = `
		exports.apply = apply;
		exports.inject = inject;
		return module.exports;
	}
});
`;
const inner = readFileSync(tmpFile, "utf8");
writeFileSync(outFile, banner + inner + "\n" + footer, "utf8");
rmSync(tmpFile, { force: true });
console.log("built:", outFile, "bytes:", (banner + inner + "\n" + footer).length);
